databases:
  - name: brainrot-db
    plan: free
    databaseName: brainrot
    user: brainrot

services:
  - type: web
    name: brainrot-trade-bot
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python webhook_app.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: brainrot-db
          property: connectionString
